### PR TITLE
Modify the submission mode

### PR DESCRIPTION
**Pull request by gslin1224**
shfit+enter to Enter

### CODE REVIEW

**Comment by satrong** [comment]
Coincidentally, we did the same thing, this is the UI I'm currently developing.

图片

**Comment by gslin1224** [comment]
> Coincidentally, we did the same thing, this is the UI I'm currently developing.
> 
> 图片

Nice Job!
I think that is better Solution

**Comment by satrong** [comment]
OK

**Comment by gslin1224** [comment]
> OK

The current typical AI websites usually do not set up such additional features. If I have to choose one, I think simply pressing Enter to submit would suffice.

**Comment by satrong** [comment]
I also get used to hitting the Enter key to submit 😀.

**Comment by sugarforever** [comment]
As the issue has been addressed by another PR https://github.com/sugarforever/chat-ollama/pull/100, thinking this PR can be closed.

Thanks.

**Pull request closed without merging**
